Ws2.8 add sighting seed data
techswitch-learners/whale-spotting-2024-sept pull request #14
Opened 2024-09-05 13:39 UTC by Purbai

Created sample data for sightings:
1. Created seedSightings.cs
2. Amended program.cs 

Checked using PGAdmin that data was loaded in the Sightings table

2024-09-06 11:12 UTC, Kiran-R-K requested changes
Good work - a couple of changes requested and I think there's been some merging issues so  let's remerge main into the branch together

2024-09-06 11:12 UTC, Kiran-R-K commented on backend/SeedData/SeedSightings.cs
> +                IsApproved = true
good idea adding some approved and some not approved sightings

2024-09-09 11:36 UTC, Kiran-R-K requested changes
I've reviewed and added another comment - let me know if you have any questions

2024-09-09 11:36 UTC, Kiran-R-K commented on backend/Program.cs
> +                var seeder = scope.ServiceProvider.GetService<SeedSightings>();
can this be renamed to 'sightingsSeeder' inline with 'speciesSeeder' naming below

2024-09-11 15:00 UTC, Purbai commented on README.md
> +
already resolved when did merge issue resolution

2024-09-12 10:21 UTC, Kiran-R-K approved these changes
well done - it's ready to go

2024-09-12 12:50 UTC, merged